---
apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
  namespace: hpe-storage
stringData:
  serviceName: truenas-csp-svc
  servicePort: "8080"
  username: hpe-storage
  password: <DELETED> # API KEY FOR TRUENAS
  backend: 192.168.80.10
