apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lab-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.80.100-192.168.80.119
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lab-pool
  namespace: metallb-system
