apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homepage
    app.kubernetes.io/name: homepage
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: IfNotPresent
          name: homepage
          ports:
            - containerPort: 3000
              name: homepage-http
              protocol: TCP
          env:
            - name: TZ
              value: "America/Denver"
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole
      restartPolicy: Always
      volumes:
        - name: pihole
          hostPath:
            path: /k8s-hostpath/pihole
            type: Directory
