---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik.bzn.bauer.mt
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-class
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`authentik.bzn.bauer.mt`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
      middlewares:
        - name: https-redirect
          namespace: traefik
        - name: security-headers
          namespace: traefik
  tls:
    secretName: authentik-bzn-bauer-mt
    options:
      name: tls-security-headers
      namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik.bzn.bauer.mt-http
  namespace: authentik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`authentik.bzn.bauer.mt`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
      middlewares:
        - name: https-redirect
          namespace: traefik
