--- # set up account for brian
- name: User Setup
  become: yes
  hosts:
    - debian
    - pve

  vars:
    username: brian
    githubname: brianbauer42
    keysurl: "https://github.com/{{ githubname }}.keys"

  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install useful packages
      ansible.builtin.package:
        name:
          - zsh
          - git
          - vim
          - curl
          - wget
          - acl #needed for ansible to set permissions on ssh keys
        state: present

    - name: Create user w/ default shell ZSH
      user:
        name: "{{ username }}"
        shell: /bin/zsh
        state: present

    - name: Add SSH keys from github
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('url', keysurl, split_lines=False) }}"

    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Allow user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^{{ username }} ALL=(ALL) NOPASSWD: ALL"
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ username }}"
          oh_my_zsh:
            theme: homelab-server
            plugins:
              - git
              - colorize
              - jsontools
              - docker
              - docker-compose
            update_mode: reminder
            update_frequency: 3

  post_tasks:
    - name: Download custom prompt for oh-my-zsh
      get_url:
        url: "https://raw.githubusercontent.com/brianbauer42/minilab/main/ansible/files/homelab-server.zsh-theme"
        dest: "/home/{{ username }}/.oh-my-zsh/custom/themes/homelab-server.zsh-theme"
