---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bauer-mt
  namespace: default
spec:
  secretName: local-bauer-mt-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.bauer.mt"
  dnsNames:
    - "local.bauer.mt"
    - "*.local.bauer.mt"
